export interface IUser {
  _id: string,
  email: string,
  isAdmin: boolean,
  kudosRenewed: number,
  kudosGiveable: number,
  kudosGranted: number,
  kudosSpendable: number,
  name: string,
  realName: string,
  canReceiveGiftsRequest: boolean,
  teamId: string,
  userId: string,
  userName: string,
}
